name: "Tests"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Run prettier
        run: npx prettier --list-different .
      - name: Run eslint
        run: npx eslint .
      - name: Lint test.ts
        run: (cd packages/node && npx tsc -p ./tsconfig.lint-test.json)
      - name: Run Tests
        run: |
          npm run test
          test -f packages/node/dist/qrcode.png || {echo "File not found"; exit 1}
      - name: Run cli and test it
        run: |
          node packages/node/lib/cli.js --opt.color white --opt.finder.round 0.5 qrcode-cli.png
          test -f qrcode-cli.png || {echo "File not found"; exit 1}
      - name: Run update-readme
        run: npm run update-readme
      - name: Run prettier on Readmes
        run: npx prettier --write "**/*.md"
      - name: Check differences
        run: git diff --exit-code
